In [48]:
from math import sqrt
import numpy as np
import pandas as pd
from sklearn import cross_validation as cv

In [112]:
df=pd.read_csv(r"C:\Users\42142\Downloads\547\project\review_sentiment.csv",sep='\t',usecols=[0,1,5])

In [153]:
df

business_id                 user_id  stars
0     ujmEBvifdJM6h6RLv4wQIg  hG7b0MtEbXx5QzbzE6C_VA    1.0
1     NZnhc2sEQy3RmzKTZnqtwQ  yXQM5uF2jS6es16SJzNHfg    5.0
2     WTqjgwHlXbSFevF32_DJVw  n6-Gk65cPZL6Uz8qRm3NYw    5.0
3     ikCg8xy5JIg_NGPx-MSIDA  dacAIZ6fTM6mqwW5uxkskg    5.0
4     b1b1eb3uo-w561D0ZfCEiQ  ssoyf2_x0EQMed6fgHeMyQ    1.0
5     eU_713ec6fTGNO4BegRaww  w31MKYsNFMrjhWxxAb5wIw    4.0
6     3fw2X5bZYeW9xCz_zGhOHg  jlu4CztcSxrKx56ba1a5AQ    3.0
7     zvO-PJCpNk4fgAVUnExYAA  d6xvYpyzcfbF_AZ8vMB7QA    1.0
8     b2jN2mm9Wf3RcrZCgfo1cg  sG_h0dIzTKWa3Q6fmb4u-g    2.0
9     oxwGyA17NL6c5t1Etg5WgQ  nMeCE5-xsdleyxYuNZ_7rA    3.0
10    8mIrX_LrOnAqWsB5JrOojQ  FIk4lQQu1eTe2EpzQ4xhBA    4.0
11    mRUVMJkUGxrByzMQ2MuOpA  -mA3-1mN4JIEkqOtdbNXCQ    1.0
12    FxLfqxdYPA6Z85PFKaqLrg  GYNnVehQeXjty0xH7-6Fhw    4.0
13    LUN6swQYa4xJKaM_UEUOEw  bAhqAPoWaZYcyYi7bs024Q    4.0
14    AakkkTuGZA2KBodKi2_u8A  TpyOT5E16YASd7EWjLQlrw    1.0
15    YvrylyuWgbP90RgMqZQVnQ  NJlxGtouq06hhC7sS2ECYw    5.0
16    NyLYY8q1-H3hfsTwuwLPCg  86J5DwcFk4f4In1Vxe2TvA    4.0
17    cHdJXLlKNWixBXpDwEGb_A  JSrP-dUmLlwZiI7Dp3PQ2A    3.0
18    6lj2BJ4tJeu7db5asGHQ4w  6Fz_nus_OG4gar721OKgZA    5.0
19    y-Iw6dZflNix4BdwIyTNGA  _N7Ndn29bpll_961oPeEfw    3.0
20    qx6WhZ42eDKmBchZDax4dQ  DzZ7piLBF-WsJxqosfJgtA    5.0
21    Mem13A3C202RzT53npn4NA  5JVY32_bmTBfIGpCCsnAfw    5.0
22    I4Nr-MVc26qWr08-S3Q1ow  3CJUJILq7CLHk_9OrvpvQg    4.0
23    d_L-rfS1vT3JMzgCUGtiow  2mxBNBeFrgDszqGS5tdEHA    5.0
24    Sfc8Haz2Yri8Mo1L0E0TsA  8NwU4TRsD3S6gIfBqFzDMQ    5.0
25    FQ1wBQb3aNeRMThSQEV0Qg  vXZeHaLvdfCPATz5BDavow    5.0
26    hd5xm20tfSa70-6UqD9-bg  vDr8hBNYigiY70fk1kF5iQ    1.0
27    Gyrez6K8f1AyR7dzW9fvAw  TTRVdTXKcq-xn6-1IWbwEw    5.0
28    9nTF596jDvBBia2EXXiOOg  q3GeSW9dWN9r_ocqFkhrvg    1.0
29    SNL64axQhCO6Z7ohcWg3wA  yxyRt-zoh_A6PMThX-h9Vw    1.0
...                      ...                     ...    ...
4970  NjDC1Evc2Wa6ykj8xVpoUw  4RG3JfK2Wki1fN70PV3V2A    5.0
4971  qy6f94ehot4zom1xpcBQfg  GHRbn-GWh7jO5xuj-S15mA    5.0
4972  CtZ3HujCLTChyoad_L-nHA  q3IwlZIHWuqx96NnJiHKIg    5.0
4973  3HQPK2X7Pcqte_vscDy3Ng  z-EXVXlocRmapIYc-X2HHQ    5.0
4974  g0yeRwvJmdd-XrH9lye0ww  52MlnjkvSLLqKKSRrbrH0w    5.0
4975  -lJtyCOTVInWusU9YF120A  dMcN3KYkypINJjLYYB-Vsg    2.0
4976  6ANVuBMmpkXpFd5Hzkn4_Q  5Cy0_FrkWONTjWiF2EWiAg    5.0
4977  faPVqws-x-5k2CQKDNtHxw  VhZdGBhmAw2pYQnWSYxhmA    5.0
4978  zidkKI_N1OPxsiddTOQH_Q  4wbYBbvjha0_sGGuGAfCQQ    5.0
4979  z9oJeVmNEc3F0ToZ0x4WuQ  e1uk-BTtgHhx-WK7wYvawg    3.0
4980  SUd3IyEN7n5OYEGyt_U5lg  1CaKHvJNbkiD_uPFcFGnIQ    5.0
4981  rTZVcJZ8G80i6NjLw0SW8Q  CrEBVkzIQs7tS-wWfaCjNQ    3.0
4982  Dx4R3jlNBZly6VLTTYjLMQ  l_wcTDlJ-rzSC5uLoaL-vA    5.0
4983  WnUttoJffplgWaQGR2J2Xw  CyPLi2BMi3N2z-E7Qpp26A    4.0
4984  QNiMs-AacTuOJwQAjmkrVA  LOzc799nxN70BYlPvR61Cw    5.0
4985  Z_-KUIoogqjFJyLNP0TW3A  2vVjPVcMfCPkpRrRNX-_SQ    5.0
4986  uuGL8diLlHfeUeFuod3F-w  _q8WHZax9PVW8zucxl588g    5.0
4987  Os1n1_idfw9vv9kwULGJnQ  Znid_azpcHmdRMHGicmkWA    5.0
4988  GyM1GVQDRUudov36NCY0Eg  NYDBZOLvZ0_rmRyDnk3ZlA    2.0
4989  R_M4P9XetEM-aLE7eHdthw  w4A4VQdCt7Om3KudYVi7vA    5.0
4990  50NTSGbZ3pN5643_K1IReA  OPN-dDUBkH7uH-G8nOnskg    4.0
4991  Z66xO_B7trDah8F0PKwRqg  pgy7Q5yvcuuL7eoukCSWEQ    5.0
4992  RkOguMKU13hPglELb6t2Vg  XKf5SC2WAXdm2jiNJiIgjQ    4.0
4993  hXY9Yq0nOLgHsWLbjam--A  Dp5OlBr36QA-0e8ZNtczpw    5.0
4994  L4e1rx1DyKKpD-or8nB-ng  Af33NzmZ2TGpwEKFxUlrlQ    5.0
4995  znWHLW1pt19HzW1VY6KfCA  upR56wFLwIXk7efFV6Nxcg    1.0
4996  ecJri9ozyke4dOCWulZiRQ  uYYVFHPgNTKDKq6pRJ0tvg    1.0
4997  eS76100l3h7Ollb5s3_M4A  k1TVjJRUyMCk0tI9ZkHCyg    4.0
4998  VUb97h3RTg6InKdfgB49Bw  Sc9fOya4inkFNttr_0z1lw    1.0
4999  l1bRQosRdqGemBnuQB5F6A  ztGtoOtbK4DRtzzrlxWvoQ    2.0

[5000 rows x 3 columns]

In [113]:
n_users,n_items = df.user_id.unique().shape[0], df.business_id.unique().shape[0]

In [114]:
n_users,n_items

(4788, 2926)

In [115]:
train_data, test_data = cv.train_test_split(df, test_size=0.25)

In [135]:
train_data.head()

business_id                 user_id  stars
923   wfNAYvc0llsjmZiSvKrIvA  dcrPeHR-s4Ei_Gw4T3za3w    1.0
2326  o69XnnmtOaj6a2sjOTsGeg  q2PVoHMhMq4Tk8lxeLFA_Q    1.0
623   sOYsxYYFl03PhHmz_rBDZQ  HTTn15w4c5Yfp4YzrZqd3g    5.0
3762  hnC15M8cEDIW-tSLf6JMSA  h0VrfhL8DjIrpP-Jqo1CpA    1.0
2035  fd5jUrbdENG7FR5C7DdINw  fs9sV78p69W1AHV8FP7Jzw    5.0

In [136]:
def construct_matrix(dataset):
    user_matrix = {}
    for (_, user_id, business_id, stars) in dataset.itertuples():
        if user_id not in user_matrix: user_matrix[user_id] = {}
        user_matrix[user_id][business_id] = stars
    return user_matrix
train_data_matrix,test_data_matrix = construct_matrix(training_set), construct_matrix(test_set)

In [149]:
train_data_matrix

{'Wgj8dI74HETaldI3dIZ7vg': {'yXS3NQ9r2eb-uvPhdvfOWQ': 4.0},
 'J4aiMaaXWXqL8ypKY7PSYA': {'UX7s-Us4HBpqVIKHazW6qA': 5.0},
 'ujHiaprwCQ5ewziu0Vi9rw': {'0zqXX2SG7UiInTtU3JhWlg': 2.0,
  '3BBiuiNLFuA-0Z4RE2UoQA': 2.0,
  '4lng77gRdpRb24o91sSihA': 2.0,
  '7zphSXBrxDGChNlNkoGSng': 2.0,
  '9kWMZaGyCn22g21Vc2ykPg': 4.0,
  'Aa7Ad3iQOyGTyVmhJ0fLeQ': 2.0,
  'Amgi3nBZZ-hny2gmQMrExA': 4.0,
  'KbaLzIBhLJZQ1HJbQXtKSw': 4.0,
  'LUb53R4GZBhcrheeSp-fhA': 5.0,
  'MuhUC0v3qBBTj6D2DO0H_w': 3.0,
  'PHIcD324vADtMQtwjjh4tw': 5.0,
  'SvMGr_Oih7ivtzmnCL-Tmg': 1.0,
  'W2WICriV5Zf03S4ETzEsiQ': 4.0,
  'WJYs12ng86_q70n4CkdkTA': 4.0,
  'X11X_7te-61E7DXewKtv7w': 2.0,
  'XBkAAhQcrXQZ6fQsEp_KDQ': 5.0,
  'cF3f4JQJ_N2IcEfTAM1-dA': 3.0,
  'cFrJfXevAc6Al5nk9iKy1A': 3.0,
  'cPcStFGBlk-6lWWsttIfVQ': 5.0,
  'j1MjZ7f1DkYnsGNZ9gTK5w': 3.0,
  'k0htNVKFkwD8hSZJ1Rdonw': 1.0,
  'mvK1pv-x0Z5rP4Hz9cWBWw': 3.0,
  'rIaFYAT3-lV7f0OSQPRVhw': 4.0,
  'rQrqrb5dFztAeFYwyqbygA': 4.0,
  'teXLmGR-kiEEVW93TCe32w': 4.0},
 'dJuxA0paONof3QiMAN8d7Q': {

In [140]:
def dot(x, y):
    if len(x) > len(y): return dot(y, x)
    return sum(value * y.get(key, 0) for (key, value) in x.items())

In [141]:
# count the nuique users in the training set
# create a mapping between the user_id and the index in the similarity matrix
num_user_train = 0
train_user_id_index = {}
for row in training_set.itertuples():
    if row[1] not in train_user_id_index: 
        train_user_id_index[row[1]] = num_user_train
        num_user_train += 1
train_user_index_id = {index: id for (id, index) in train_user_id_index.items()}

In [151]:
train_user_index_id

{0: 'Wgj8dI74HETaldI3dIZ7vg',
 1: 'J4aiMaaXWXqL8ypKY7PSYA',
 2: 'ujHiaprwCQ5ewziu0Vi9rw',
 3: 'dJuxA0paONof3QiMAN8d7Q',
 4: 'ibFdignja_hNpgCjDYP7Ug',
 5: 'BdSCZkjNh_Y6nmI_9TPn2Q',
 6: 'E5-BcXKtQ1_cA87yY_Apww',
 7: '0uasL7MepHHQrVNgIhdG3g',
 8: '81H_yEsSDHcy2rXZ7EwsZw',
 9: 'diaiQrxYFU1V5qxrFnW9fg',
 10: 'A2rZyprdbtKvSzhd2yK_dQ',
 11: 'p-8AMN9Q0qwym-3Pdle20Q',
 12: 'RU2VtVZG8to-XVEHD-2qag',
 13: 'nWx5GEaJ1dpc-psAbG_v5Q',
 14: 'G9jwU3O0HOXTHt43eJi2mg',
 15: 'qCljcbAEvp-y-wXTjsUrpw',
 16: 'oxwGyA17NL6c5t1Etg5WgQ',
 17: 'n9oHe5CpcrHyH8nOCFJhHA',
 18: 'thLX_k20SPJ0KyusGTBIHw',
 19: 'sWwCwjsd27k0Y8m1RIWZEg',
 20: 'nnsaEGT-0TW9ZMN0OMgqSg',
 21: 'CqS6xaF4ZmZFWbxWv5zz0A',
 22: 'd_L-rfS1vT3JMzgCUGtiow',
 23: 'bpZx9D6E2tIwNPJAOpy20A',
 24: 'c_iQzwsTDYraPvHSKz88QA',
 25: 'wPWnFZMl8gDdHwbo5_VdMA',
 26: 'obzBY9Pea6nUXsjtEjo-Cw',
 27: 'ILA41PhErg4bl1royzDX4g',
 28: '1NJPR31R-LNvDTcY_NaPmQ',
 29: 'CGUK3cd2gxp2q3KPY19Oog',
 30: 'pDMxIQoqkZJeUe2r8XIVKQ',
 31: 'vT5mKKEcAxhSPj452HHspw',
 32: 'O6-BlCviQBIE

In [142]:
square_sum = np.zeros(num_user_train)
mean_rating = np.zeros(num_user_train)
for i in range(num_user_train):
    user_ratings = train_matrix[train_user_index_id[i]]
    square_sum[i] = sqrt(sum(value ** 2 for value in user_ratings.values()))
    mean_rating[i] = sum(value for value in user_ratings.values()) * 1.0 / len(user_ratings)
    # with this mean, we can normalize the ratings
    for business_id in user_ratings.keys():
        user_ratings[business_id] -= mean_rating[i]

In [148]:
square_sum

array([ 0.        ,  0.        ,  6.04648658, ...,  0.        ,
        0.        ,  0.        ])

In [145]:
user_simi = np.zeros((num_user_train, num_user_train))
for i in range(num_user_train):
    print (i)
    for j in range(num_user_train):
        # because the ratings has been normalized, the similarity might be negative,
        # in that case, we just set the similarity to be zero
        user_simi[i][j] = max(dot(train_matrix[train_user_index_id[i]], train_matrix[train_user_index_id[j]]) \
                / (square_sum[i] * square_sum[j]), 0)
simi_sum = np.sum(user_simi, axis = 0)
simi_sum

0
1
2
3
4
5
6

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys



7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280

1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066


array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [146]:
user_simi

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,   1., ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [130]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
         x#You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis]) 
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])     
    return pred

In [152]:
item_prediction = predict(train_data_matrix, item_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

AttributeError: 'dict' object has no attribute 'dot'

In [138]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')

TypeError: float() argument must be a string or a number, not 'dict'